services:
  - type: web
    name: smartqueue-api
    rootDir: server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false

  - type: web
    name: smartqueue-web
    rootDir: client
    env: static
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: smartqueue-api
          property: url
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
      - type: redirect
        source: /api/(.*)
        destination: https://smartqueue-api.onrender.com/api/$1
